global:
  scrape_interval: 5s
  scrape_timeout: 5s

  # Scrape targets to execute
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']
    labels:
      job: 'prometheus'
      instance: 'prometheus'
- job_name:  'postgres'
  static_configs:
  - targets: ['psql_exporter:9187']
    labels:
      job: 'postgres'
      instance: 'postgres'
