#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Corriendo prod"
python /django_app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
